import {assertInteger,assertNonEmptyString,assertPlainObject,assertTimestamp,deepFreeze,jsonClone} from "../contracts/contract-utils.js";
export const RUNTIME_EVENT_SCHEMA_VERSION=1;
export const RUNTIME_EVENT_TYPES=Object.freeze(["learner-response-submitted","deterministic-evaluation-completed","llm-invocation-recorded","reasoning-interpretation-completed","diagnostic-evidence-created","pedagogical-decision-created","coach-output-created","learner-evidence-created","learner-evidence-invalidated","supplemental-evidence-created","learner-state-projected","evaluation-recorded","experiment-assigned","visual-routing-shadow-recorded","visual-live-shadow-claim-recorded","visual-live-shadow-observation-recorded"]);
function enumValue(value,allowed,label){if(!allowed.includes(value))throw new TypeError(`${label} is invalid`);return value;}
function optionalString(value,label){if(value===null||value===undefined||value==="")return null;return assertNonEmptyString(String(value),label).trim();}
function stableJson(value){if(Array.isArray(value))return`[${value.map(stableJson).join(",")}]`;if(value&&typeof value==="object")return`{${Object.keys(value).sort().map((key)=>`${JSON.stringify(key)}:${stableJson(value[key])}`).join(",")}}`;return JSON.stringify(value);}
export function defineRuntimeEvent({eventId,type,aggregateType,aggregateId,sequence,occurredAtUtc,idempotencyKey,learnerKey=null,domainId=null,sessionId=null,attemptId=null,payload,provenance={}}={}){assertNonEmptyString(eventId,"runtime eventId");enumValue(type,RUNTIME_EVENT_TYPES,"runtime event type");assertNonEmptyString(aggregateType,"runtime aggregateType");assertNonEmptyString(aggregateId,"runtime aggregateId");assertInteger(sequence,"runtime event sequence",{min:1});assertTimestamp(occurredAtUtc,"runtime occurredAtUtc");assertNonEmptyString(idempotencyKey,"runtime idempotencyKey");assertPlainObject(provenance,"runtime provenance");return deepFreeze({schemaVersion:RUNTIME_EVENT_SCHEMA_VERSION,eventId:eventId.trim(),type,aggregateType:aggregateType.trim(),aggregateId:aggregateId.trim(),sequence,occurredAtUtc,idempotencyKey:idempotencyKey.trim(),learnerKey:optionalString(learnerKey,"runtime learnerKey"),domainId:optionalString(domainId,"runtime domainId"),sessionId:optionalString(sessionId,"runtime sessionId"),attemptId:optionalString(attemptId,"runtime attemptId"),payload:jsonClone(payload,"runtime payload"),provenance:jsonClone(provenance,"runtime provenance")});}
export function validateRuntimeEvent(event){if(event?.schemaVersion!==RUNTIME_EVENT_SCHEMA_VERSION)throw new TypeError("runtime event schemaVersion is invalid");return defineRuntimeEvent(event);}
export class RuntimeEventConflictError extends Error{constructor(message){super(`Runtime event conflict: ${message}`);this.name="RuntimeEventConflictError";}}
export function createInMemoryRuntimeEventStore(seed=[]){const events=[],byId=new Map(),byIdempotency=new Map(),lastSequence=new Map();function append(rawEvent){const event=validateRuntimeEvent(rawEvent);const idempotent=byIdempotency.get(event.idempotencyKey);if(idempotent){if(stableJson(idempotent)!==stableJson(event))throw new RuntimeEventConflictError(`idempotency key ${event.idempotencyKey} was reused with different content`);return idempotent;}if(byId.has(event.eventId))throw new RuntimeEventConflictError(`eventId ${event.eventId} already exists`);const aggregateKey=`${event.aggregateType}::${event.aggregateId}`,expected=(lastSequence.get(aggregateKey)??0)+1;if(event.sequence!==expected)throw new RuntimeEventConflictError(`${aggregateKey} expected sequence ${expected}, received ${event.sequence}`);events.push(event);byId.set(event.eventId,event);byIdempotency.set(event.idempotencyKey,event);lastSequence.set(aggregateKey,event.sequence);return event;}for(const event of seed)append(event);return Object.freeze({append,eventForId(eventId){return byId.get(String(eventId))??null;},eventForIdempotencyKey(idempotencyKey){return byIdempotency.get(String(idempotencyKey))??null;},eventsForAggregate(aggregateType,aggregateId){const keyType=String(aggregateType),keyId=String(aggregateId);return events.filter((event)=>event.aggregateType===keyType&&event.aggregateId===keyId);},eventsForAttempt(attemptId){const key=String(attemptId);return events.filter((event)=>event.attemptId===key);},eventsForLearner(learnerKey,{domainId=null}={}){const key=String(learnerKey);return events.filter((event)=>event.learnerKey===key&&(domainId===null||event.domainId===String(domainId)));},allEvents(){return[...events];},nextSequence(aggregateType,aggregateId){return(lastSequence.get(`${aggregateType}::${aggregateId}`)??0)+1;},size(){return events.length;}});}
