(function(){
  if(!window.AdaptiveCoach||!window.CancellationHeartsTutorAdapter) return;
  const {AdaptiveCoachCore,SELF_LEVELS}=window.AdaptiveCoach;
  const core=new AdaptiveCoachCore(window.CancellationHeartsTutorAdapter);
  let exercise=null,stepIndex=0,answers={},walkthroughIndex=0;
  const steps=[
    {id:'objective',label:'1. Objective'},{id:'control',label:'2. Control state'},{id:'cards',label:'3. Cards that create it'},{id:'next',label:'4. Next objective'},{id:'preserve',label:'5. Preserve for later'}
  ];
  function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
  function labelCard(code){return window.CancellationHeartsTutorAdapter.cardLabel(code);}
  function handStrip(compact=false,highlight=[]){
    if(!exercise) return '';
    const hi=new Set(highlight.filter(c=>exercise.hand.includes(c)));
    return `<div class="tutor-card hand-card ${compact?'persistent-hand':''}"><div class="eyebrow">${exercise.source==='curated'?'Curated teaching hand':'Transfer hand'}</div><h3>${esc(exercise.title)}</h3><div class="tutor-hand">${exercise.hand.map(c=>`<span class="mini-card ${/[DH]$/.test(c)?'red':''} ${hi.has(c)?'tutor-highlight':''}">${esc(labelCard(c))}</span>`).join('')}</div></div>`;
  }
  function ensureUI(){
    if(document.getElementById('tutorRoot')) return;
    const gameMode=document.getElementById('gameMode');
    if(gameMode&&!gameMode.querySelector('option[value="tutor"]')){const o=document.createElement('option');o.value='tutor';o.textContent='Tutor mode';gameMode.appendChild(o);}
    const root=document.createElement('section');root.id='tutorRoot';root.className='tutor-root hidden';
    root.innerHTML=`<div class="tutor-shell"><div class="tutor-top"><div><h2>Adaptive Tutor</h2><p>Learn to build a hand pathway, not merely pick a card.</p></div><button id="tutorExit" class="secondary compact">Exit Tutor</button></div><div id="tutorBody"></div></div>`;
    document.getElementById('app').appendChild(root);
    document.getElementById('tutorExit').onclick=()=>window.location.reload();
    const btn=document.getElementById('newGameBtn');
    if(btn)btn.addEventListener('click',e=>{if(document.getElementById('gameMode').value==='tutor'){e.stopImmediatePropagation();e.preventDefault();startTutor();}},true);
    if(gameMode){const old=gameMode.onchange;gameMode.onchange=function(){if(old)old.call(this);document.getElementById('newGameBtn').textContent=this.value==='tutor'?'Start Tutor':(this.value==='practice'?'Start Moon Practice':'Start New Game');};}
  }
  function startTutor(){
    document.body.classList.add('tutor-mode-active');document.documentElement.classList.add('tutor-mode-active');window.scrollTo(0,0);
    document.getElementById('setup').classList.add('hidden');const game=document.getElementById('game');if(game)game.classList.add('hidden');document.getElementById('tutorRoot').classList.remove('hidden');
    if(!core.profile.selfLevel)renderSelfAssessment();else beginExercise();
  }
  function renderSelfAssessment(){
    const body=document.getElementById('tutorBody');
    body.innerHTML=`<div class="tutor-card"><h3>First, assess your current level</h3><p>This only sets the starting scaffolding. Your actual performance will quickly override it.</p><div class="level-grid">${Object.entries(SELF_LEVELS).map(([k,v])=>`<button class="level-choice" data-level="${k}"><strong>${v.label}</strong><span>${v.description}</span></button>`).join('')}</div></div>`;
    body.querySelectorAll('.level-choice').forEach(b=>b.onclick=()=>{core.selfAssess(b.dataset.level);beginExercise();});
  }
  function beginExercise(){exercise=core.selectExercise();stepIndex=0;answers={};walkthroughIndex=0;renderExerciseIntro();window.scrollTo({top:0,behavior:'instant'});}
  function validateWalkthrough(stages){
    const hand=new Set(exercise?.hand||[]);
    return stages.map(stage=>({...stage,highlight:(stage.highlight||[]).filter(c=>hand.has(c))}));
  }
  function beginnerWalkthroughStages(expert){
    if(exercise?.id==='guided-useful-void'){
      return validateWalkthrough([
        {title:'1. I want to accomplish X',highlight:['AS','10S','JH','8H','KC','JD'],body:`<p><strong>First, I do not choose the shortest suit.</strong> I ask which cards are most likely to trap me later.</p><p>A♠ is the clearest danger because it can easily become a forced winner. 10♠ and J♥ can also become harder to lose as higher cards disappear. K♣ and J♦ are not harmless either; they can take control at inconvenient times.</p><div class="framework-callout"><strong>X:</strong> Keep enough low cards to stay flexible while creating a safe way to get rid of A♠ and any other card that starts becoming hard to lose.</div>`},
        {title:'2. To accomplish X, I need control or no control',highlight:['3C','4D','4H','AS'],body:`<p>At the start, I mostly want <strong>no control</strong>. My low cards, especially 3♣, 4♦, and 4♥, give me ways to follow without taking tricks.</p><p>I do not want to win a trick just because I can. I only want control when taking the lead lets me create a specific disposal route for A♠ or another dangerous card.</p><div class="framework-callout"><strong>Control state:</strong> Stay off lead unless winning lets me deliberately create or use a useful void.</div>`},
        {title:'3. I can obtain that state with these specific cards',highlight:['3C','8C','KC','4D','4H','AS'],body:`<p>Now I look at the cards that matter to this first phase.</p><ul><li><strong>3♣:</strong> valuable low club and possible safe exit.</li><li><strong>8♣ and K♣:</strong> the cards I would need to lose if clubs are going to become a void.</li><li><strong>4♦ and 4♥:</strong> low cards worth preserving because they help me stay off lead later.</li><li><strong>A♠:</strong> the main card I want a future void to carry out of my hand.</li></ul><p>The key question is not “Which suit is shortest?” It is “Which suit can I realistically empty while opponents are still likely to lead it again?”</p>`},
        {title:'4. Once X happens, what changes?',highlight:['3C','8C','KC','AS'],body:`<p>Suppose I manage to lose K♣ and 8♣ while keeping 3♣ for later.</p><p>Now 3♣ becomes my last club. That changes its job. If I can safely get rid of 3♣, I become void in clubs.</p><p>The void matters only if clubs are still likely to be led afterward. If another player later leads a club, I can use that trick to discard A♠ instead of being forced to follow suit.</p><div class="framework-callout"><strong>State change:</strong> K♣ and 8♣ gone → 3♣ becomes the card that can finish clubs → club void can become an A♠ disposal route.</div>`},
        {title:'5. Once X happens, my next objective becomes Y',highlight:['3C','AS','4D','4H'],body:`<p>Now the next objective is concrete: <strong>finish clubs without sacrificing all of my other low exits, then use a later club lead to unload A♠.</strong></p><p>I still preserve 4♦ and 4♥ because after I dump A♠ I do not want to be trapped on lead with only medium and high cards.</p><div class="causal-chain"><strong>lose K♣ and 8♣ safely</strong><span>→</span><strong>3♣ becomes last club</strong><span>→</span><strong>get rid of 3♣</strong><span>→</span><strong>become void in clubs</strong><span>→</span><strong>discard A♠ on a later club lead</strong></div>`},
        {title:'6. The complete pathway',highlight:['KC','8C','3C','AS','4D','4H'],body:`<p>The whole plan is:</p><div class="causal-chain vertical"><strong>stay off lead while possible</strong><span>↓</span><strong>identify A♠ as the main future danger</strong><span>↓</span><strong>lose K♣ and 8♣ before they trap me</strong><span>↓</span><strong>preserve 3♣ until it can finish the club suit safely</strong><span>↓</span><strong>create the club void only if clubs are still likely to be led later</strong><span>↓</span><strong>use that club lead to dump A♠</strong><span>↓</span><strong>keep 4♦ or 4♥ as a low way to surrender the lead afterward</strong></div><p>The lesson is simple: a void is useful only when it has a job. Here, the job is to create a realistic route for A♠ to leave the hand.</p>`}
      ]);
    }
    return validateWalkthrough([
      {title:'1. I want to accomplish X',highlight:['QS','QH','10H','9H','QC','10D'],body:`<p><strong>First, I do not choose a card.</strong> I ask what can trap this hand later.</p><p>The main problems are Q♠, the medium-high heart block, Q♣, and 10♦. My first objective is to <strong>keep enough low cards to stay flexible while shedding cards that may become forced winners, without stripping the protection under Q♠.</strong></p><div class="framework-callout"><strong>X:</strong> Stay off lead early, shed future winners while they can still lose, and keep Q♠ protected.</div>`},
      {title:'2. To accomplish X, I need control or no control',highlight:['QC','10D','KD'],body:`<p>For this first objective, I mostly want <strong>no control</strong>.</p><p>Q♣ and 10♦ are easier to lose while someone else is leading their suits. Taking the lead now does not solve my main problem.</p><p>K♦ is different. I keep it as <strong>optional future control</strong>, but I do not want it to win until I can name exactly what I will lead next and why.</p><div class="framework-callout"><strong>Control state:</strong> Stay off lead now. Preserve K♦ as a possible later entry.</div>`},
      {title:'3. I can obtain that state with these specific cards',highlight:['QC','10D','2S','5C','6D'],body:`<p>Now I assign jobs only to the cards that matter to this phase.</p><ul><li><strong>Q♣:</strong> shed while higher clubs can still beat it.</li><li><strong>10♦:</strong> shed before it becomes hard to lose.</li><li><strong>2♠:</strong> preserve because it protects Q♠.</li><li><strong>5♣ and 6♦:</strong> preserve as low cards that can help me avoid taking the lead later.</li></ul><p>I do not need to explain all 13 cards yet. I only need to know which cards create or protect the position I want right now.</p>`},
      {title:'4. Once X happens, what changes?',highlight:['5C','QS','QH','10H'],body:`<p>Imagine Q♣ has now been safely lost.</p><p>That changes the meaning of 5♣. It is no longer just a low club. It may become the <strong>last club in my hand</strong>.</p><p>If I can later get rid of 5♣, I become void in clubs. That matters because a future club lead can carry Q♠, Q♥, or 10♥ out of my hand.</p><div class="framework-callout"><strong>State change:</strong> Q♣ gone → 5♣ becomes a route to a purposeful club void.</div>`},
      {title:'5. Once X happens, my next objective becomes Y',highlight:['KD','5C','QS','2S'],body:`<p>Now I can name a concrete next objective.</p><p>If Q♣ is gone and 5♣ is my last club, K♦ can become a useful entry card:</p><div class="causal-chain"><strong>K♦ wins</strong><span>→</span><strong>lead 5♣</strong><span>→</span><strong>finish clubs</strong><span>→</span><strong>become void in clubs</strong><span>→</span><strong>use a future club lead to dispose of Q♠ or a dangerous heart</strong></div><p>This is what makes the K♦ win useful. Without that follow-up, I would rather remain off lead.</p><p><strong>Preserve 2♠</strong> while Q♠ still depends on it. Solving the club problem is not worth creating a spade problem.</p>`},
      {title:'6. The complete pathway',highlight:['QC','10D','2S','KD','5C','QS','QH'],body:`<p>Now the whole plan can be stated as one sequence:</p><div class="causal-chain vertical"><strong>stay off lead</strong><span>↓</span><strong>shed Q♣ and 10♦ while they can still lose</strong><span>↓</span><strong>preserve 2♠ under Q♠</strong><span>↓</span><strong>after Q♣ is gone, 5♣ can become the last club</strong><span>↓</span><strong>use K♦ as an entry only when K♦ → 5♣ advances the plan</strong><span>↓</span><strong>create the club void</strong><span>↓</span><strong>use that void to dispose of Q♠ or the dangerous heart block</strong></div><p>The expert is not following a fixed script. The point is to keep asking: what am I trying to make true, do I want the lead or not, which cards help me create that position, what does that unlock next, and what must I keep for later?</p>`}
    ]);
  }
  function renderFullExpertReference(expert){
    const suitData=expert.suitPlan||expert.suitPlans||[];const controlData=expert.controlPlans||expert.controlBranches||[];const cardData=expert.cardPlan||expert.cardRoles||[];
    return `<details class="expert-reference"><summary>Review the full expert hand map</summary>${suitData.length?`<h4>Suit map</h4><div class="suit-plan-grid">${suitData.map(v=>`<div class="worked-block"><h4>${esc(v.suit||v.name||'Suit')}</h4><p>${esc(v.plan||v.text||v)}</p></div>`).join('')}</div>`:''}${controlData.length?`<h4>Alternative control lines</h4><div class="control-plan-list">${controlData.map((b,i)=>`<div class="control-plan"><div class="control-plan-title">${esc(b.entry||'Entry')} line ${i+1}</div><p><strong>When:</strong> ${esc(b.condition)}</p><p><strong>Then:</strong> ${esc(b.followUp)}</p><p><strong>Purpose:</strong> ${esc(b.creates||b.resultingState)}</p></div>`).join('')}</div>`:''}${cardData.length?`<h4>All 13 card roles</h4><div class="card-plan-table"><div class="card-plan-head"><span>Card</span><span>Current role</span><span>Plan</span><span>Why</span><span>Role changes when…</span></div>${cardData.map(r=>`<div class="card-plan-row"><strong class="role-card">${esc(labelCard(r.card||''))}</strong><span>${esc(r.role)}</span><span>${esc(r.action)}</span><span>${esc(r.why)}</span><span>${esc(r.changes)}</span></div>`).join('')}</div>`:''}</details>`;
  }
  function renderExerciseIntro(){
    const body=document.getElementById('tutorBody');const expert=window.CancellationHeartsTutorAdapter.expertModel(exercise);const show=core.shouldShowWorkedExample();
    if(show&&core.profile.selfLevel==='beginner'){renderWorkedWalkthrough();return;}
    body.innerHTML=`${handStrip()}<div class="tutor-card worked-card"><h3>${show?'Expert model':'Your turn first'}</h3>${show?`<p><strong>Expert read:</strong> ${esc(expert.read)}</p><p><strong>Strategy:</strong> ${esc(expert.strategy)}</p><ol>${expert.pathway.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:`<p>Build the pathway before seeing the expert model. The tutor will give feedback one link at a time.</p>`}<button id="beginPathway" class="primary">${show?'Practice this pathway':'Build my pathway'}</button></div>`;
    document.getElementById('beginPathway').onclick=()=>{if(show)core.recordWorkedExample();renderStep();window.scrollTo({top:0,behavior:'smooth'});};
  }
  function renderWorkedWalkthrough(){
    const expert=window.CancellationHeartsTutorAdapter.expertModel(exercise);const stages=beginnerWalkthroughStages(expert);const stage=stages[walkthroughIndex];const body=document.getElementById('tutorBody');
    body.innerHTML=`${handStrip(true,stage.highlight)}<div class="walkthrough-progress">${stages.map((_,i)=>`<span class="${i<walkthroughIndex?'done':i===walkthroughIndex?'active':''}">${i+1}</span>`).join('')}</div><div class="tutor-card expert-led"><div class="eyebrow">Expert think-aloud</div><h3>${esc(stage.title)}</h3>${stage.body}<div class="tutor-actions"><button id="walkNext" class="primary">${walkthroughIndex===stages.length-1?'Finish worked example':'Continue with the expert'}</button>${walkthroughIndex>0?'<button id="walkBack" class="secondary">Back</button>':''}</div>${walkthroughIndex===stages.length-1?renderFullExpertReference(expert):''}</div>`;
    document.getElementById('walkNext').onclick=()=>{if(walkthroughIndex<stages.length-1){walkthroughIndex++;renderWorkedWalkthrough();window.scrollTo({top:0,behavior:'smooth'});}else{core.recordWorkedExample();renderStep();window.scrollTo({top:0,behavior:'smooth'});}};
    const back=document.getElementById('walkBack');if(back)back.onclick=()=>{walkthroughIndex--;renderWorkedWalkthrough();window.scrollTo({top:0,behavior:'smooth'});};
  }
  function renderStep(){
    const step=steps[stepIndex],prompt=exercise.prompts[step.id],mode=core.scaffoldMode(skillKeys(step.id));const body=document.getElementById('tutorBody');
    body.innerHTML=`${handStrip(true)}<div class="tutor-progress">${steps.map((s,i)=>`<div class="${i<stepIndex?'done':i===stepIndex?'active':''}">${s.label}</div>`).join('')}</div><div class="tutor-grid"><div class="tutor-card"><h3>${esc(step.label)}</h3><p class="tutor-question">${esc(prompt.question)}</p><textarea id="tutorAnswer" rows="5" placeholder="Explain your thinking..."></textarea><div class="tutor-actions"><button id="submitTutorAnswer" class="primary">Submit thinking</button>${mode.showFallback?'<button id="showChoices" class="secondary">I need choices</button>':''}</div><div id="choiceBox"></div></div><div class="tutor-card pathway-live"><h3>Your developing pathway</h3>${renderPathwaySoFar()}</div></div>`;
    document.getElementById('submitTutorAnswer').onclick=()=>submitStep({text:document.getElementById('tutorAnswer').value});const showChoices=document.getElementById('showChoices');if(showChoices)showChoices.onclick=()=>renderChoices(prompt.fallback);if(mode.fallbackOpen)renderChoices(prompt.fallback);
  }
  function renderChoices(choices){const box=document.getElementById('choiceBox');if(!box)return;box.innerHTML=`<div class="fallback-box"><p><strong>Fallback choices</strong></p>${choices.map((x,i)=>`<button class="choice-option" data-i="${i}">${esc(x)}</button>`).join('')}</div>`;box.querySelectorAll('.choice-option').forEach(b=>b.onclick=()=>submitStep({choice:choices[+b.dataset.i]}));}
  function skillKeys(id){return {objective:['objective_reasoning','causal_planning_state_transition'],control:['control_reasoning','causal_planning_control_requirements'],cards:['entry_selection','queen_structure','effective_winner_reasoning'],next:['useful_void_reasoning','causal_planning_state_transition'],preserve:['exit_preservation','causal_planning_preservation']}[id]||['hand_reading'];}
  function submitStep(response){const step=steps[stepIndex];if(!(response.text||response.choice)){document.getElementById('tutorAnswer')?.focus();return;}const result=core.evaluate(step,response,{exercise,answers});answers[step.id]=response.text||response.choice;renderFeedback(step,result,response);}
  function renderFeedback(step,result,response){
    const body=document.getElementById('tutorBody');const level=result.score>=0.8?'Strong reasoning':result.score>=0.58?'Good start':'Needs another look';
    body.innerHTML=`${handStrip(true)}<div class="tutor-grid"><div class="tutor-card"><div class="feedback-badge score-${result.score>=0.8?'high':result.score>=0.58?'mid':'low'}">${level}</div><h3>Your thinking</h3><p>${esc(response.text||response.choice)}</p><h3>Tutor feedback</h3><p>${esc(result.feedback)}</p>${result.score<0.58?`<div class="hint-panel"><strong>Scaffold</strong><p>${esc(hintFor(step.id))}</p></div>`:''}<div class="tutor-actions"><button id="continueTutor" class="primary">${stepIndex===steps.length-1?'Review full pathway':'Continue'}</button>${result.score<0.5?'<button id="retryTutor" class="secondary">Revise answer</button>':''}</div></div><div class="tutor-card pathway-live"><h3>Your developing pathway</h3>${renderPathwaySoFar()}</div></div>`;
    document.getElementById('continueTutor').onclick=()=>{stepIndex++;if(stepIndex>=steps.length)renderReview();else renderStep();window.scrollTo({top:0,behavior:'smooth'});};const r=document.getElementById('retryTutor');if(r)r.onclick=()=>renderStep();
  }
  function hintFor(id){return {objective:'Do not start with the shortest suit or highest card. Ask what future problem is most likely to trap you.',control:'Ask whether winning the lead helps the objective or merely gives opponents a chance to dump points on you.',cards:'Name the exact cards doing jobs: protection, entry, exit, or future-winner liability.',next:'A successful phase should create a new opportunity. What becomes possible only after X succeeds?',preserve:'Which low or control card looks expendable now but has a job in the next phase?'}[id]||'Work backward from the future position you want.';}
  function renderPathwaySoFar(){const labels={objective:'I want to accomplish X',control:'To accomplish X, I need',cards:'I can obtain that state with',next:'Once X happens, my next objective becomes Y',preserve:'These cards must be preserved because Y depends on them'};return steps.map(s=>`<div class="pathway-line"><span>${labels[s.id]}</span><strong>${esc(answers[s.id]||'…')}</strong></div>`).join('');}
  function renderReview(){const expert=window.CancellationHeartsTutorAdapter.expertModel(exercise);const body=document.getElementById('tutorBody');const weak=core.masterySummary().slice(0,4);body.innerHTML=`${handStrip(true)}<div class="tutor-grid"><div class="tutor-card"><h3>Your pathway</h3>${renderPathwaySoFar()}<h3>Expert pathway</h3><ol>${expert.pathway.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>${renderFullExpertReference(expert)}</div><div class="tutor-card"><h3>Adaptive profile</h3><p>The tutor will use these estimates to choose how much scaffolding and what kind of next hand you receive.</p>${weak.map(x=>`<div class="mastery-row"><span>${esc(x.skill.replaceAll('_',' '))}</span><strong>${Math.round(x.value*100)}%</strong></div>`).join('')}<button id="nextTutorHand" class="primary">Next hand</button></div></div>`;document.getElementById('nextTutorHand').onclick=beginExercise;}
  ensureUI();window.CancellationHeartsTutor={core,start:startTutor};
})();