import { domainAdapterSupports, validateDomainAdapter } from "./domain-adapter.js";
import {
  defineCalibrationObservation,
  defineItemCalibrationLifecycleRecord,
  validateAssessmentEvidence,
  validateCalibrationArtifact,
  validateCalibrationObservation,
  validateItemCalibrationLifecycleRecord
} from "./contracts/index.js";

export const CALIBRATION_CORE_SCHEMA_VERSION = 1;
export const CALIBRATION_CORE_OBSERVATION_STATUSES = Object.freeze(["eligible", "excluded"]);
export const CALIBRATION_CORE_SNAPSHOT_STATUSES = Object.freeze(["insufficient-data","descriptive-signal","fit-candidate"]);
export const DEFAULT_CALIBRATION_CORE_POLICY = Object.freeze({
  descriptiveUniqueLearners:30,descriptiveMinimumOutcomeCount:5,fitCandidateUniqueLearners:100,fitCandidateMinimumOutcomeCount:20,
  shadowArtifactUniqueLearners:100,shadowArtifactObservations:500,selectionReadyUniqueLearners:300,selectionReadyObservations:2000,
  selectionReadyItemEffectiveSample:100,empiricalModelKinds:Object.freeze(["rasch-1pl","irt-2pl"])
});
const ITEM_LIFECYCLE_TRANSITIONS=Object.freeze({generated:Object.freeze(["content-validated","retired"]),"content-validated":Object.freeze(["experimental","retired"]),experimental:Object.freeze(["calibrating","retired"]),calibrating:Object.freeze(["calibrated","experimental","retired"]),calibrated:Object.freeze(["operational","calibrating","retired"]),operational:Object.freeze(["calibrating","retired"]),retired:Object.freeze([])});
function finite(value){return Number.isFinite(Number(value));}
function freeze(value){if(Array.isArray(value))return Object.freeze(value.map(freeze));if(!value||typeof value!=="object")return value;return Object.freeze(Object.fromEntries(Object.entries(value).map(([key,entry])=>[key,freeze(entry)])));}
function unique(values=[]){return[...new Set(values.filter(value=>typeof value==="string"&&value.trim()).map(value=>value.trim()))];}
function normalizedPolicy(overrides={}){const policy={...DEFAULT_CALIBRATION_CORE_POLICY,...overrides,empiricalModelKinds:[...(overrides.empiricalModelKinds??DEFAULT_CALIBRATION_CORE_POLICY.empiricalModelKinds)]};for(const key of ["descriptiveUniqueLearners","descriptiveMinimumOutcomeCount","fitCandidateUniqueLearners","fitCandidateMinimumOutcomeCount","shadowArtifactUniqueLearners","shadowArtifactObservations","selectionReadyUniqueLearners","selectionReadyObservations","selectionReadyItemEffectiveSample"])if(!Number.isInteger(policy[key])||policy[key]<0)throw new TypeError(`calibration policy ${key} must be a nonnegative integer`);if(!Array.isArray(policy.empiricalModelKinds)||!policy.empiricalModelKinds.length)throw new TypeError("calibration policy empiricalModelKinds must be a non-empty array");return freeze(policy);}
function wilsonInterval(successes,total,z=1.96){if(!total)return{low:null,high:null};const p=successes/total,z2=z*z,denominator=1+z2/total,center=(p+z2/(2*total))/denominator,margin=z*Math.sqrt((p*(1-p)+z2/(4*total))/total)/denominator;return{low:Number(Math.max(0,center-margin).toFixed(4)),high:Number(Math.min(1,center+margin).toFixed(4))};}
function scoreOutcome(score){if(score?.scale!=="dichotomous"||score.value===null||score.value===undefined)return null;if(Number(score.value)===Number(score.max))return 1;if(Number(score.value)===Number(score.min))return 0;return null;}
function snapshotStatus({uniqueLearners,correct,incorrect},policy){if(uniqueLearners>=policy.fitCandidateUniqueLearners&&correct>=policy.fitCandidateMinimumOutcomeCount&&incorrect>=policy.fitCandidateMinimumOutcomeCount)return"fit-candidate";if(uniqueLearners>=policy.descriptiveUniqueLearners&&correct>=policy.descriptiveMinimumOutcomeCount&&incorrect>=policy.descriptiveMinimumOutcomeCount)return"descriptive-signal";return"insufficient-data";}
function artifactValidationFailure(message){throw new TypeError(`calibration artifact policy validation failed: ${message}`);}
function normalizedDifficulty(parameterSet){const value=parameterSet?.parameters?.normalizedDifficulty;return finite(value)&&Number(value)>=0&&Number(value)<=1?Number(value):null;}
function currentDescriptor(adapter,itemOrId){const descriptor=adapter.itemDescriptor(itemOrId);if(!descriptor)throw new TypeError("calibration core requires an item descriptor");return descriptor;}

export function createCalibrationCore(adapter,{policy:policyOverrides={}}={}){
  validateDomainAdapter(adapter);if(!domainAdapterSupports(adapter,"calibration"))throw new TypeError(`domain ${adapter.domainId} does not declare calibration capability`);const policy=normalizedPolicy(policyOverrides);
  function prepareObservation(evidence,{observationId=null,cohort={},metadata={}}={}){const validated=validateAssessmentEvidence(evidence);if(validated.domainId!==adapter.domainId)throw new TypeError("assessment evidence domainId must match calibration core domainId");const reasons=[];if(validated.eligibility.calibration!==true)reasons.push(...validated.eligibility.exclusionReasons,"assessment-evidence-not-calibration-eligible");if(validated.administration.firstResponse!==true)reasons.push("not-first-response");if(validated.administration.firstEncounter!==true)reasons.push("not-first-encounter");if(validated.administration.independent!==true)reasons.push("not-independent");if(validated.score.value===null||validated.score.value===undefined)reasons.push("unscored-response");const exclusionReasons=unique(reasons);if(exclusionReasons.length)return freeze({schemaVersion:CALIBRATION_CORE_SCHEMA_VERSION,status:"excluded",evidenceId:validated.evidenceId,domainId:validated.domainId,itemVersionId:validated.item.itemVersionId,exclusionReasons,observation:null});const observation=defineCalibrationObservation({observationId:observationId??`${validated.evidenceId}:calibration`,domainId:validated.domainId,learnerKey:validated.learnerKey,item:validated.item,submittedAtUtc:validated.timing.submittedAtUtc,score:validated.score,administration:validated.administration,eligibility:validated.eligibility,confidence:validated.confidence,responseTimeMs:validated.timing.elapsedMs,cohort,metadata:{...metadata,sourceAssessmentEvidenceId:validated.evidenceId,sourceAssessmentSessionId:validated.sessionId}});return freeze({schemaVersion:CALIBRATION_CORE_SCHEMA_VERSION,status:"eligible",evidenceId:validated.evidenceId,domainId:validated.domainId,itemVersionId:validated.item.itemVersionId,exclusionReasons:[],observation});}
  function buildDescriptiveSnapshot(records=[]){if(!Array.isArray(records))throw new TypeError("calibration snapshot records must be an array");const eligible=[],excluded=[];for(const record of records){if(record?.status==="excluded"){excluded.push(record);continue;}const candidate=record?.status==="eligible"?record.observation:record;try{const observation=validateCalibrationObservation(candidate);if(observation.domainId!==adapter.domainId)throw new TypeError("observation domain mismatch");if(scoreOutcome(observation.score)===null){excluded.push(freeze({schemaVersion:CALIBRATION_CORE_SCHEMA_VERSION,status:"excluded",evidenceId:observation.metadata?.sourceAssessmentEvidenceId??null,domainId:observation.domainId,itemVersionId:observation.itemVersionId,exclusionReasons:["descriptive-difficulty-requires-dichotomous-score"],observation:null}));continue;}eligible.push(observation);}catch(error){excluded.push(freeze({schemaVersion:CALIBRATION_CORE_SCHEMA_VERSION,status:"excluded",evidenceId:null,domainId:adapter.domainId,itemVersionId:null,exclusionReasons:[`invalid-calibration-observation:${error.message}`],observation:null}));}}
    const grouped=new Map();for(const observation of eligible){const key=observation.itemVersionId;if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(observation);}const items=[...grouped.entries()].map(([itemVersionId,observations])=>{const first=observations[0],outcomes=observations.map(entry=>scoreOutcome(entry.score)),correct=outcomes.filter(value=>value===1).length,incorrect=outcomes.filter(value=>value===0).length,learners=new Set(observations.map(entry=>entry.learnerKey)),successRate=observations.length?correct/observations.length:null,descriptor=first.item;return freeze({itemId:descriptor.itemId,itemVersionId,fingerprint:descriptor.fingerprint,constructIds:descriptor.constructIds,observations:observations.length,uniqueLearners:learners.size,correct,incorrect,successRate:successRate===null?null:Number(successRate.toFixed(4)),rawDifficulty:successRate===null?null:Number((1-successRate).toFixed(4)),successRateWilson95:wilsonInterval(correct,observations.length),status:snapshotStatus({uniqueLearners:learners.size,correct,incorrect},policy),interpretation:"descriptive-only-cohort-confounded-not-empirical-item-difficulty"});}).sort((a,b)=>a.itemVersionId.localeCompare(b.itemVersionId));const uniqueLearners=new Set(eligible.map(entry=>entry.learnerKey)).size;return freeze({schemaVersion:CALIBRATION_CORE_SCHEMA_VERSION,domainId:adapter.domainId,status:items.some(entry=>entry.status==="fit-candidate")?"fit-candidate":items.some(entry=>entry.status==="descriptive-signal")?"descriptive-signal":"insufficient-data",observationCount:eligible.length,excludedCount:excluded.length,uniqueLearners,items,excluded,safeguards:{source:"A3-assessment-evidence",firstResponseOnly:true,firstEncounterOnly:true,independentOnly:true,descriptiveDifficultyIsNotIrtDifficulty:true,noLiveSelectionOverrideFromSnapshot:true}});}
  function validateArtifact(artifact){const validated=validateCalibrationArtifact(artifact);if(validated.domainId!==adapter.domainId)artifactValidationFailure("artifact domainId does not match adapter domainId");if(validated.status==="rejected")return validated;if(!policy.empiricalModelKinds.includes(validated.model.kind))artifactValidationFailure(`unsupported empirical model kind ${validated.model.kind}`);if(validated.validation?.connectedDesign!==true)artifactValidationFailure("connected calibration design is required");if(!finite(validated.validation?.holdoutLogLoss)||!finite(validated.validation?.baselineLogLoss))artifactValidationFailure("held-out and baseline log loss are required");if(Number(validated.validation.holdoutLogLoss)>=Number(validated.validation.baselineLogLoss))artifactValidationFailure("held-out log loss must improve over baseline");if(validated.status==="shadow-only"&&(validated.sample.uniqueLearners<policy.shadowArtifactUniqueLearners||validated.sample.observations<policy.shadowArtifactObservations))artifactValidationFailure("shadow-only artifact does not meet minimum cohort thresholds");if(validated.status==="selection-ready"&&(validated.sample.uniqueLearners<policy.selectionReadyUniqueLearners||validated.sample.observations<policy.selectionReadyObservations))artifactValidationFailure("selection-ready artifact does not meet minimum cohort thresholds");for(const parameterSet of validated.itemParameters){if(normalizedDifficulty(parameterSet)===null)artifactValidationFailure(`item ${parameterSet.itemVersionId} requires normalizedDifficulty in [0,1]`);if(validated.status==="selection-ready"&&parameterSet.effectiveSampleSize<policy.selectionReadyItemEffectiveSample)artifactValidationFailure(`selection-ready item ${parameterSet.itemVersionId} has insufficient effective sample`);}return validated;}
  function difficultyForItem(itemOrId,artifact=null,{allowShadow=false}={}){const descriptor=currentDescriptor(adapter,itemOrId),prior=adapter.difficultyPrior(itemOrId),priorResult=freeze({value:prior?.value??null,source:prior?.source??"expert-prior",empirical:false,artifactId:null,artifactStatus:artifact?.status??null,itemVersionId:descriptor.itemVersionId,fingerprint:descriptor.fingerprint,reason:artifact?"empirical-artifact-not-applicable":"no-empirical-artifact"});if(!artifact)return priorResult;const validated=validateArtifact(artifact),allowed=validated.status==="selection-ready"||(allowShadow&&validated.status==="shadow-only");if(!allowed)return priorResult;const parameterSet=validated.itemParameters.find(entry=>entry.itemVersionId===descriptor.itemVersionId)??null;if(!parameterSet||parameterSet.itemFingerprint!==descriptor.fingerprint)return priorResult;const difficulty=normalizedDifficulty(parameterSet);if(difficulty===null)return priorResult;return freeze({value:difficulty,source:`empirical-${validated.model.kind}`,empirical:true,artifactId:validated.artifactId,artifactStatus:validated.status,itemVersionId:descriptor.itemVersionId,fingerprint:descriptor.fingerprint,effectiveSampleSize:parameterSet.effectiveSampleSize,standardError:parameterSet.standardErrors?.difficulty??parameterSet.standardErrors?.normalizedDifficulty??null,discrimination:parameterSet.parameters?.discrimination??null,reason:"exact-version-and-fingerprint-match"});}
  function createLifecycleRecord(itemOrId,{state="generated",updatedAtUtc=new Date().toISOString(),empiricalArtifactId=null,metadata={}}={}){const item=currentDescriptor(adapter,itemOrId);return defineItemCalibrationLifecycleRecord({domainId:adapter.domainId,item,state,updatedAtUtc,empiricalArtifactId,metadata});}
  function transitionLifecycle(record,nextState,{updatedAtUtc=new Date().toISOString(),empiricalArtifactId=record?.empiricalArtifactId??null,metadata={}}={}){const validated=validateItemCalibrationLifecycleRecord(record);if(validated.domainId!==adapter.domainId)throw new TypeError("calibration lifecycle record domainId must match adapter domainId");const allowed=ITEM_LIFECYCLE_TRANSITIONS[validated.state]??[];if(!allowed.includes(nextState))throw new TypeError(`calibration transition ${validated.state} -> ${nextState} is not allowed`);return defineItemCalibrationLifecycleRecord({domainId:validated.domainId,item:validated.item,state:nextState,updatedAtUtc,empiricalArtifactId,metadata:{...validated.metadata,...metadata}});}
  return freeze({schemaVersion:CALIBRATION_CORE_SCHEMA_VERSION,domainId:adapter.domainId,policy,prepareObservation,buildDescriptiveSnapshot,validateArtifact,difficultyForItem,createLifecycleRecord,transitionLifecycle});
}
