export const REGRESSION_CASES=Object.freeze([
 {id:'multi-part-listening',problemId:'guided-queen-protection',stepId:'objective',text:'I want to avoid allowing the 10h, Qh and Qs from becoming forced winners.',expected:{status:'correct',noRedundantQuestion:true,grounded:true}},
 {id:'terse-clubs',problemId:'guided-useful-void',stepId:'objective',text:'Clubs',expected:{requiresClarification:true,noReasoningMastery:true,grounded:true}},
 {id:'useful-void-liabilities',problemId:'guided-useful-void',stepId:'objective',text:'If the void allowed me a safe way to lose the As and the Jh, as well as any other potential forced winners',expected:{grounded:true,noStaleQueenCards:true}},
 {id:'stay-off-lead-terse',problemId:'guided-useful-void',stepId:'control',text:'Stay off lead',expected:{requiresClarification:true,noReasoningMastery:true,grounded:true}},
 {id:'passing-other-card-mentions',problemId:'guided-useful-void',stepId:'prepass_pathway',text:'I want to keep 3C and 4D as low exits while passing KC, 8C and AS so that I reduce liabilities now and then reassess the disposal route. Pass cards: KC, 8C, AS',expected:{status:'correct',grounded:true}},
 {id:'correct-conclusion-wrong-reason',problemId:'guided-useful-void',stepId:'objective',text:'Clubs is best because the shortest suit is always the best void.',expected:{mustNotAdvance:true,grounded:true}},
 {id:'later-part-first',problemId:'guided-queen-protection',stepId:'objective',text:'My objective is to prevent those cards from becoming forced winners later.',expected:{mustIdentifyMissing:true,grounded:true}},
 {id:'contradiction-control',problemId:'guided-queen-protection',stepId:'control',text:'I want to stay off lead, but my immediate objective is to take control now even though I do not have a follow-up.',expected:{mustNotAdvance:true,grounded:true}},
 {id:'defensible-alternative',problemId:'guided-queen-protection',stepId:'control',text:'I would normally stay off lead, but if Q clubs is already gone and 5 clubs is my last club, I would allow K diamonds to win so I can lead 5 clubs and create a disposal route.',expected:{mustNotReject:true,grounded:true}},
 {id:'moon-minimum-intervention',problemId:'guided-useful-void',stepId:'pivot',text:'If the moon threat becomes credible, I would make the smallest play needed to break it and then return to my original avoidance pathway.',expected:{status:'correct',grounded:true}},
 {id:'moon-terse-stop-is-not-enough',problemId:'guided-useful-void',stepId:'pivot',text:'Stop the moon.',expected:{mustNotAdvance:true,grounded:true}},
 {id:'preserve-queen-protection-unicode',problemId:'guided-queen-protection',stepId:'preserve',text:'I want to preserve 2♠ because it protects Q♠ through another spade round, plus a separate low exit such as 5♣ so I can surrender the lead later.',expected:{status:'correct',noRedundantQuestion:true,grounded:true}},
 {id:'preserve-queen-protection-card-names',problemId:'guided-queen-protection',stepId:'preserve',text:'I want to preserve 2 of spades because it protects the queen of spades through another spade round, plus a separate low exit such as 5 of clubs so I can surrender the lead later.',expected:{status:'correct',noRedundantQuestion:true,grounded:true}},
 {id:'queen-protection-cards-card-names',problemId:'guided-queen-protection',stepId:'cards',text:'2 of spades and 9 of spades protect the queen of spades, so I want to preserve 2 of spades longest while shedding queen of clubs and 10 of diamonds before they promote into winners.',expected:{status:'correct',noRedundantQuestion:true,grounded:true}},
 {id:'targeting-conditional',problemId:'guided-useful-void',stepId:'target',text:'I would target a player only if they had demonstrated a void or exposed high cards and the score justified the risk; otherwise I would leave them alone.',expected:{status:'correct',grounded:true}}
]);
export const ALTERNATIVE_PATHWAYS=Object.freeze([
 {id:'queen-default-off-lead',problemId:'guided-queen-protection',stepId:'control',classification:'strong',text:'I want to stay off lead early because other players leading gives me chances to shed Q clubs, 10 diamonds and high hearts while I preserve the low spades under Q spades.'},
 {id:'queen-conditional-club-route',problemId:'guided-queen-protection',stepId:'control',classification:'defensible',text:'If Q clubs has already left and 5 clubs is my last club, I would let K diamonds take control so I can lead 5 clubs, finish clubs, and create a later disposal route.'},
 {id:'queen-conditional-spade-round',problemId:'guided-queen-protection',stepId:'control',classification:'defensible',text:'If the queen of spades is still protected and higher spades are live, I can use K diamonds to gain control and then lead 2 spades to induce another spade round without exposing the queen yet.'},
 {id:'queen-control-without-followup',problemId:'guided-queen-protection',stepId:'control',classification:'weak',text:'I want K diamonds to win because taking control is always better than letting someone else lead.'},
 {id:'void-default-off-lead',problemId:'guided-useful-void',stepId:'control',classification:'strong',text:'I want to stay off lead while other players help me lose clubs, because the club void only matters if it later gives A spades a safe disposal route.'},
 {id:'void-conditional-control',problemId:'guided-useful-void',stepId:'control',classification:'defensible',text:'If winning the lead lets me immediately lead a club and shorten the suit toward a useful void, I am willing to take control for that specific follow-up.'}
]);
export const PASSING_SCENARIOS=Object.freeze([
 {id:'pass-pathway-sensible',problemId:'guided-useful-void',stepId:'prepass_pathway',text:'I want to reduce the cards most likely to trap me while keeping low exits, so that after the pass I can reassess suit shape and build a useful disposal route. Pass cards: KC, 8C, AS',expected:{status:'correct'}},
 {id:'pass-pathway-unicode-cards',problemId:'guided-useful-void',stepId:'prepass_pathway',text:'I want to reduce the cards most likely to trap me while keeping low exits, so that after the pass I can reassess suit shape and build a useful disposal route. Pass cards: K♣, 8♣, A♠',expected:{status:'correct'}},
 {id:'pass-pathway-card-names',problemId:'guided-useful-void',stepId:'prepass_pathway',text:'I want to reduce the cards most likely to trap me while keeping low exits, so that after the pass I can reassess suit shape and build a useful disposal route. Pass cards: king of clubs, 8 of clubs, ace of spades',expected:{status:'correct'}},
 {id:'pass-pathway-objective-noun-phrase',problemId:'guided-queen-protection',stepId:'prepass_pathway',text:'I want the pass to reduce liabilities while preserving low exits, so that afterward I can build a useful disposal route and reassess. Pass cards: K♦, Q♣, Q♠',expected:{status:'correct'}},
 {id:'pass-high-cards-by-rank-only',problemId:'guided-useful-void',stepId:'prepass_pathway',text:'I want to pass KC, AS and JH because they are three high cards and high cards are bad. Then I will just play whatever is left. Pass cards: KC, AS, JH',expected:{mustNotAdvance:true}},
 {id:'pass-damages-queen-protection',problemId:'guided-queen-protection',stepId:'prepass_pathway',text:'I want to pass 2S, 9S and 5C to make my hand lower and then get rid of other high cards later. Pass cards: 2S, 9S, 5C',expected:{mustNotAdvance:true}},
 {id:'shortest-suit-not-enough',problemId:'guided-useful-void',stepId:'prepass_pathway',text:'I want to pass KC, 8C and 3C because clubs are shortest, so making a void there must be best. Then I will decide what to do. Pass cards: KC, 8C, 3C',expected:{mustNotAdvance:true}},
 {id:'postpass-real-revision',problemId:'guided-useful-void',stepId:'postpass_pathway',text:'The incoming cards made spades more dangerous, so my first objective now is to stay off lead while I find a safer route to unload AS. I will preserve my low exits because I need them after the disposal succeeds.',expected:{status:'correct'}},
 {id:'postpass-refuses-revision',problemId:'guided-useful-void',stepId:'postpass_pathway',text:'The incoming cards changed the hand, but I will use exactly the same plan regardless because I already chose it before the pass. I will keep my low cards.',expected:{mustNotAdvance:true}}
]);
export const ADVANCED_SCENARIOS=Object.freeze([
 {id:'moon-premature-one-heart',problemId:'guided-useful-void',stepId:'threat',text:'As soon as anyone wins one heart trick, I assume they are shooting the moon and abandon my plan.',expected:{mustNotAdvance:true}},
 {id:'moon-evidence-credible',problemId:'guided-useful-void',stepId:'threat',text:'I treat the moon as credible only if the same player keeps collecting penalty cards and still appears to control the lead across several tricks.',expected:{status:'correct'}},
 {id:'moon-minimum-intervention',problemId:'guided-useful-void',stepId:'pivot',text:'I make the smallest intervention needed to put one penalty card on somebody else, then return to my original pathway instead of taking over the whole hand.',expected:{status:'correct'}},
 {id:'moon-overreaction',problemId:'guided-useful-void',stepId:'pivot',text:'I would abandon my whole plan and try to take every remaining trick so the suspected moon shooter cannot win anything else.',expected:{mustNotAdvance:true}},
 {id:'observe-before-target',problemId:'guided-useful-void',stepId:'observe',text:'Before targeting, I want to see a demonstrated void, exposed high cards, lost protection, or repeated forced wins that show the player is actually constrained.',expected:{status:'correct'}},
 {id:'scoreboard-only-targeting',problemId:'guided-useful-void',stepId:'observe',text:'I only need the scoreboard. If someone has the most points, that alone tells me their hand is vulnerable.',expected:{mustNotAdvance:true}},
 {id:'conditional-targeting',problemId:'guided-useful-void',stepId:'target',text:'I target only when a demonstrated void or exposed high cards make the pressure likely to work and the score payoff justifies the risk; otherwise I keep my own pathway.',expected:{status:'correct'}},
 {id:'target-leader-without-evidence',problemId:'guided-useful-void',stepId:'target',text:'I always target whoever is leading the score even if I have no evidence about their cards.',expected:{mustNotAdvance:true}},
 {id:'cancellation-evidence',problemId:'guided-useful-void',stepId:'observe',text:'I also want to see whether duplicate ranks have already appeared, because cancellation can change which high card is actually exposed or forced to win.',expected:{status:'correct'}},
 {id:'carryover-urgency',problemId:'guided-useful-void',stepId:'threat',text:'If a large carried penalty pot is waiting and the same player still controls the lead, that raises the cost of waiting, so I would treat the threat as more urgent.',expected:{status:'correct'}}
]);
