export const SIMULATION_SOURCE='synthetic-simulation';
export const RESPONSE_CLASSES=Object.freeze(['clearly-correct','clearly-incorrect','incomplete','ambiguous','correct-conclusion-wrong-reasoning','wrong-conclusion-sound-reasoning','strategically-defensible-alternative','contradictory','terse-potentially-correct','uninterpretable']);
export const SKILL_KEYS=Object.freeze(['objective','control','cards','next','preserve','prepass_pathway','postpass_pathway','threat','pivot','observe','target','transfer']);
function req(v,name){if(typeof v!=='string'||!v.trim())throw new TypeError(`${name} is required`);return v.trim();}
function prob(v,name){const n=Number(v);if(!Number.isFinite(n)||n<0||n>1)throw new TypeError(`${name} must be in [0,1]`);return n;}
export function defineSimulatedLearnerProfile(input={}){const trueSkillProfile={};for(const key of SKILL_KEYS)trueSkillProfile[key]=prob(input.trueSkillProfile?.[key]??.5,`trueSkillProfile.${key}`);return Object.freeze({source:SIMULATION_SOURCE,learnerId:req(input.learnerId,'learnerId'),declaredSkillLevel:req(input.declaredSkillLevel||'unknown','declaredSkillLevel'),trueSkillProfile:Object.freeze(trueSkillProfile),reasoningStyle:req(input.reasoningStyle||'causal','reasoningStyle'),confidenceStyle:req(input.confidenceStyle||'calibrated','confidenceStyle'),verbosityStyle:req(input.verbosityStyle||'medium','verbosityStyle'),errorTendencies:Object.freeze([...(input.errorTendencies||[])]),strategyBiases:Object.freeze([...(input.strategyBiases||[])]),adaptationRate:prob(input.adaptationRate??.5,'adaptationRate'),hintDependence:prob(input.hintDependence??.25,'hintDependence'),ambiguityRate:prob(input.ambiguityRate??.1,'ambiguityRate'),contradictionRate:prob(input.contradictionRate??.05,'contradictionRate')});}
export function defineSimulatedResponse(input={}){if(!RESPONSE_CLASSES.includes(input.expectedResponseClass))throw new TypeError(`invalid response class ${input.expectedResponseClass}`);return Object.freeze({source:SIMULATION_SOURCE,handId:req(input.handId,'handId'),stepId:req(input.stepId,'stepId'),learnerProfileId:req(input.learnerProfileId,'learnerProfileId'),intendedReasoningState:Object.freeze({...input.intendedReasoningState}),responseText:String(input.responseText??''),expectedResponseClass:input.expectedResponseClass,conclusionCorrect:Boolean(input.conclusionCorrect),reasoningCorrect:Boolean(input.reasoningCorrect),reasoningExplicit:Boolean(input.reasoningExplicit),complete:Boolean(input.complete),contradictsEarlierAnswer:Boolean(input.contradictsEarlierAnswer),assistanceState:req(input.assistanceState||'none','assistanceState'),simulationSeed:Number(input.simulationSeed)||0,passCards:Array.isArray(input.passCards)?Object.freeze([...input.passCards]):Object.freeze([]),metadata:Object.freeze({...input.metadata})});}
export function sanitizeSyntheticAssessmentEvidence(evidence){const clone=structuredClone(evidence);clone.eligibility={...clone.eligibility,learnerModel:false,calibration:false,exclusionReasons:[...new Set([...(clone.eligibility?.exclusionReasons||[]),SIMULATION_SOURCE])]};clone.metadata={...clone.metadata,source:SIMULATION_SOURCE,synthetic:true};return clone;}
export function simulationRecord(payload={}){return Object.freeze({source:SIMULATION_SOURCE,createdAtUtc:new Date().toISOString(),...payload});}
