import {defineSimulatedResponse} from './contracts.mjs';
export function mulberry32(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
const RANK={2:2,3:3,4:4,5:5,6:6,7:7,8:8,9:9,10:10,J:11,Q:12,K:13,A:14};
function topThree(hand=[]){return [...hand].sort((a,b)=>(RANK[b.slice(0,-1)]||0)-(RANK[a.slice(0,-1)]||0)).slice(0,3);}
function lowCards(hand=[]){return [...hand].sort((a,b)=>(RANK[a.slice(0,-1)]||0)-(RANK[b.slice(0,-1)]||0)).slice(0,2);}
function suit(code){return code.slice(-1);}
function goodText(stepId,problem,passCards){const hand=problem.hand||[],hasQS=hand.includes('QS'),lows=lowCards(hand).join(' and ');switch(stepId){
 case'objective':return hasQS?'I want to keep QS protected while shedding QH, 10H, QC and other future winners before they become forced winners.':'I want to create a useful disposal route only if it gives me a safe way to unload AS or another future winner while preserving low exits.';
 case'control':return'I want to stay off lead at first. I would take control only when winning creates a named follow-up, such as leading a low card to finish a useful void or advance a safe disposal route.';
 case'cards':return hasQS?'2S and 9S protect QS, while QC, 10D, QH and 10H are liabilities I want to shed.':'AS and JH are liabilities; KC or JD are conditional control cards, while low cards remain exits.';
 case'next':return'Once the first objective succeeds, I want to use the new state to dump the most dangerous remaining future winner, then get off lead again.';
 case'preserve':return`I want to preserve ${lows||'my lowest exits'} because the next phase depends on having a safe way to surrender control.`;
 case'prepass_pathway':return`I want the pass to reduce liabilities while preserving low exits, so that afterward I can build a useful disposal route and reassess. Pass cards: ${passCards.join(', ')}`;
 case'postpass_pathway':return'The incoming cards changed the hand shape, so I am reassessing rather than blindly keeping the old plan. My first objective now is to stay off lead while I shed the new liabilities, and I will preserve my lowest exits for the phase after that.';
 case'threat':return'I would treat a moon attempt as credible if one player keeps collecting hearts or QS and still appears to control the lead. I would wait for that evidence before changing my plan.';
 case'pivot':return'I would make the minimum intervention needed to break the moon threat and then return to my original avoidance pathway so I preserve as much future choice as possible.';
 case'observe':return'Before targeting, I want to see a demonstrated void, exposed high cards, lost protection, repeated forced wins, or cancellation evidence that shows the player is actually vulnerable.';
 case'target':return'I would target a player only if their demonstrated void or exposed high cards make the play likely to work and the score justifies the risk; otherwise I would not target them.';
 default:return'I would choose the line that preserves future choice and revise it when the live card state changes.';}}
function incompleteText(stepId,problem,passCards){switch(stepId){case'objective':return'Keep the dangerous cards from becoming winners.';case'control':return'Stay off lead.';case'cards':return'AS and JH.';case'next':return'Dump a dangerous card.';case'preserve':return'Keep a low card.';case'prepass_pathway':return`I want to get rid of high cards. Pass cards: ${passCards.join(', ')}`;case'postpass_pathway':return'The incoming cards changed things, so I would adjust.';case'threat':return'Watch for someone shooting the moon.';case'pivot':return'Stop the moon.';case'observe':return'Watch the other players.';case'target':return'Target whoever looks weak.';default:return'Not sure.';}}
function wrongText(stepId,problem,passCards){switch(stepId){case'objective':return'Clubs are shortest, so I should always make a club void first.';case'control':return'I should take the lead immediately because winning control is always good.';case'cards':return'The lowest cards are the dangerous ones, so I should spend all of them first.';case'next':return'Once I make a void I should immediately regain the lead and keep winning.';case'preserve':return'No cards need preserving because I should shed everything as fast as possible.';case'prepass_pathway':return`I am passing the three highest cards just because high cards are bad. Pass cards: ${passCards.join(', ')}`;case'postpass_pathway':return'The incoming cards do not matter; I will use exactly the same plan no matter what.';case'threat':return'I would abandon my plan as soon as anyone wins a heart trick because they are probably shooting the moon.';case'pivot':return'I would take every remaining trick so the moon shooter cannot win anything.';case'observe':return'I only need the scoreboard to know who is vulnerable.';case'target':return'I always target the current leader even without evidence about their hand.';default:return'I would maximize the current trick without worrying about the rest of the hand.';}}
function terseText(stepId){return({objective:'Clubs',control:'Stay off lead',cards:'AS',next:'Dump it',preserve:'Low card',threat:'Moon',pivot:'Break it',observe:'Voids',target:'Leader'})[stepId]||'Maybe';}
export function generateSimulatedResponse({persona,problem,stepId,seed=1,previousAnswers={}}={}){const rng=mulberry32(seed),skill=persona.trueSkillProfile?.[stepId]??persona.trueSkillProfile?.transfer??.5,passCards=topThree(problem.hand||[]);let cls='clearly-correct';if(rng()<persona.contradictionRate)cls='contradictory';else if(rng()<persona.ambiguityRate)cls='ambiguous';else if(rng()<skill*.68)cls='clearly-correct';else if(skill>.72&&rng()<.18)cls='strategically-defensible-alternative';else if(rng()<.45)cls='incomplete';else cls='clearly-incorrect';if(persona.reasoningStyle==='conclusion-first'&&rng()<.55)cls='terse-potentially-correct';if(persona.errorTendencies.includes('control-without-purpose')&&stepId==='control')cls='clearly-incorrect';if(persona.errorTendencies.includes('target-before-evidence')&&stepId==='target')cls='clearly-incorrect';if(persona.errorTendencies.includes('abandon-plan-on-moon-signal')&&stepId==='pivot')cls='clearly-incorrect';if(persona.errorTendencies.includes('pass-as-card-dump')&&stepId==='prepass_pathway')cls='correct-conclusion-wrong-reasoning';if(persona.errorTendencies.includes('answers-one-component')&&rng()<.6)cls='incomplete';let text,conclusionCorrect=false,reasoningCorrect=false,explicit=true,complete=false;if(cls==='clearly-correct'||cls==='strategically-defensible-alternative'){text=goodText(stepId,problem,passCards);conclusionCorrect=reasoningCorrect=complete=true;}else if(cls==='terse-potentially-correct'){text=terseText(stepId);conclusionCorrect=true;explicit=false;}else if(cls==='incomplete'||cls==='ambiguous'){text=incompleteText(stepId,problem,passCards);conclusionCorrect=true;reasoningCorrect=cls==='incomplete';explicit=cls==='incomplete';}else if(cls==='correct-conclusion-wrong-reasoning'){text=stepId==='prepass_pathway'?wrongText(stepId,problem,passCards):`${goodText(stepId,problem,passCards).split('.')[0]} because the shortest suit is always best.`;conclusionCorrect=true;reasoningCorrect=false;}else if(cls==='contradictory'){text=stepId==='control'?'I want to stay off lead, but I also want to take control immediately even though I have no follow-up.':`${goodText(stepId,problem,passCards)} But I would also do the opposite immediately.`;conclusionCorrect=false;reasoningCorrect=false;}else{text=wrongText(stepId,problem,passCards);explicit=true;}return defineSimulatedResponse({handId:problem.id,stepId,learnerProfileId:persona.learnerId,intendedReasoningState:{skill,previousAnswers},responseText:text,expectedResponseClass:cls,conclusionCorrect,reasoningCorrect,reasoningExplicit:explicit,complete,contradictsEarlierAnswer:cls==='contradictory',assistanceState:'none',simulationSeed:seed,passCards});}
