import {defineSimulatedLearnerProfile} from './contracts.mjs';
const skill=(base,overrides={})=>({objective:base,control:base,cards:base,next:base,preserve:base,prepass_pathway:base,postpass_pathway:base,threat:base,pivot:base,observe:base,target:base,transfer:Math.max(0,base-.08),...overrides});
export const SIMULATED_PERSONAS=Object.freeze([
 defineSimulatedLearnerProfile({learnerId:'beginner-trick-by-trick',declaredSkillLevel:'beginner',trueSkillProfile:skill(.28,{objective:.35,control:.2,preserve:.18,prepass_pathway:.18,postpass_pathway:.12,threat:.1,pivot:.08,observe:.08,target:.08}),reasoningStyle:'local-trick',verbosityStyle:'short',errorTendencies:['shortest-suit-equals-best-void','shed-highest-reflex'],strategyBiases:['immediate-trick'],adaptationRate:.35,hintDependence:.7,ambiguityRate:.25,contradictionRate:.1}),
 defineSimulatedLearnerProfile({learnerId:'beginner-good-instinct-weak-explanation',declaredSkillLevel:'beginner',trueSkillProfile:skill(.43,{objective:.58,cards:.55,control:.42,preserve:.32,transfer:.28}),reasoningStyle:'conclusion-first',verbosityStyle:'terse',errorTendencies:['unstated-reasoning'],strategyBiases:['reasonable-instinct'],adaptationRate:.55,hintDependence:.5,ambiguityRate:.4,contradictionRate:.05}),
 defineSimulatedLearnerProfile({learnerId:'developing-weak-contingency',declaredSkillLevel:'developing',trueSkillProfile:skill(.67,{objective:.78,control:.72,cards:.72,next:.74,preserve:.68,prepass_pathway:.65,postpass_pathway:.5,threat:.42,pivot:.35,observe:.4,target:.38,transfer:.56}),reasoningStyle:'pathway',verbosityStyle:'medium',errorTendencies:['late-pivot'],strategyBiases:['preserve-original-plan'],adaptationRate:.6,hintDependence:.3,ambiguityRate:.12,contradictionRate:.06}),
 defineSimulatedLearnerProfile({learnerId:'developing-over-controller',declaredSkillLevel:'developing',trueSkillProfile:skill(.63,{objective:.72,control:.38,cards:.68,next:.68,preserve:.61,prepass_pathway:.64,postpass_pathway:.58}),reasoningStyle:'control-seeking',verbosityStyle:'medium',errorTendencies:['control-without-purpose'],strategyBiases:['take-lead'],adaptationRate:.55,hintDependence:.32,ambiguityRate:.1,contradictionRate:.08}),
 defineSimulatedLearnerProfile({learnerId:'advanced-over-targeter',declaredSkillLevel:'advanced',trueSkillProfile:skill(.78,{objective:.86,control:.82,cards:.82,next:.84,preserve:.8,prepass_pathway:.76,postpass_pathway:.75,threat:.8,pivot:.74,observe:.6,target:.48,transfer:.7}),reasoningStyle:'table-aggressive',verbosityStyle:'medium',errorTendencies:['target-before-evidence'],strategyBiases:['pressure-score-leader'],adaptationRate:.68,hintDependence:.16,ambiguityRate:.08,contradictionRate:.06}),
 defineSimulatedLearnerProfile({learnerId:'advanced-moon-overreactor',declaredSkillLevel:'advanced',trueSkillProfile:skill(.8,{threat:.9,pivot:.46,observe:.78,target:.76,transfer:.72}),reasoningStyle:'threat-sensitive',verbosityStyle:'medium',errorTendencies:['abandon-plan-on-moon-signal'],strategyBiases:['moon-defense'],adaptationRate:.7,hintDependence:.14,ambiguityRate:.06,contradictionRate:.05}),
 defineSimulatedLearnerProfile({learnerId:'advanced-weak-passing',declaredSkillLevel:'advanced',trueSkillProfile:skill(.79,{prepass_pathway:.42,postpass_pathway:.5,objective:.88,control:.84,preserve:.85,threat:.82,pivot:.8,observe:.8,target:.78,transfer:.7}),reasoningStyle:'whole-hand',verbosityStyle:'long',errorTendencies:['pass-as-card-dump'],strategyBiases:['in-hand-optimization'],adaptationRate:.66,hintDependence:.18,ambiguityRate:.05,contradictionRate:.04}),
 defineSimulatedLearnerProfile({learnerId:'expert-like',declaredSkillLevel:'expert',trueSkillProfile:skill(.93,{transfer:.88}),reasoningStyle:'causal-multistage',verbosityStyle:'medium',errorTendencies:[],strategyBiases:['manage-future-choice'],adaptationRate:.85,hintDependence:.04,ambiguityRate:.02,contradictionRate:.02}),
 defineSimulatedLearnerProfile({learnerId:'expert-overconfident',declaredSkillLevel:'expert',trueSkillProfile:skill(.86,{target:.78,pivot:.8,transfer:.78}),reasoningStyle:'confident-causal',confidenceStyle:'overconfident',verbosityStyle:'long',errorTendencies:['subtle-overcommitment'],strategyBiases:['decisive-lines'],adaptationRate:.72,hintDependence:.03,ambiguityRate:.02,contradictionRate:.1}),
 defineSimulatedLearnerProfile({learnerId:'cautious-incomplete',declaredSkillLevel:'developing',trueSkillProfile:skill(.7,{transfer:.58}),reasoningStyle:'partial-causal',confidenceStyle:'underconfident',verbosityStyle:'short',errorTendencies:['answers-one-component'],strategyBiases:['avoid-commitment'],adaptationRate:.62,hintDependence:.38,ambiguityRate:.33,contradictionRate:.03})
]);
export function personaById(id){return SIMULATED_PERSONAS.find(p=>p.learnerId===id)||null;}
